services:
  http:
    build:
      context: .
      dockerfile: apps/http/Dockerfile
    image: http_image
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}

  ws:
    build:
      context: .
      dockerfile: apps/ws/Dockerfile
    image: ws_image
    ports:
      - "3001:3001"
    environment:
      - WS_PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}